### PR TITLE
Changed HTTP cookie to HTTP only to make the solution more secure

### PR DESCRIPTION
**Pull request by ThomasArdal**

### CODE REVIEW

**Comment by ThomasArdal** [comment]
@PureKrome Can you see what the problem is here?

**Comment by PureKrome** [comment]
Taken from this random guy on the interwebs called something something Coding Horror something something .. (tehehehe 😄 )

>When you tag a cookie with the HttpOnly flag, it tells the browser that this particular cookie should only be accessed by the server. Any attempt to access the cookie from client script is strictly forbidden. Of course, this presumes you have:
>
>A modern web browser
>A browser that actually implements HttpOnly correctly

[ref linkage](https://blog.codinghorror.com/protecting-your-cookies-httponly/).

So yep - very important IMO. Don't want people to read OTHER PEOPLE's cookies.

**Comment by ThomasArdal** [comment]
@PureKrome Yeah I know. That's why I created the PR :smile:

My question were around the failing AppVeyor build. But I see that you already merged it, so not a problem any longer.

👍

**Comment by PureKrome** [comment]
@ThomasArdal new NUGET added up. https://ci.appveyor.com/project/PureKrome/simpleauthentication-xud0a

I didn't bother porting the NS because it's too painful with the current code base. I.e. it's more than 60 mins of work 😢

**Pull request merged**
