### PR TITLE
Add Support for LinkedIn provider

### PR DESCRIPTION
**Pull request by Dashue**
Hey,

Please review and let me know if anything needs fixing.
I tried with my own linkedin application, but redacted the keys when checking in, perhaps you have an app to be used for testing with?

It seems that linkedin is missing the following information: UserName, Locale, Gender. Not sure what to do about those.

Looking forward to getting your feedback!

Cheers

### CODE REVIEW

**Comment by PureKrome** [comment]
Hi @Dashue - thanks heaps for submitting a PR.

Personally I hate LinkedIn but heaps of people still use em - and I guess for Authentication also :smile: 

Ok .. so this is coded against the current production code (even though that's the `dev` branch, which is perfect). I've started work (well, nearly finished now) on some massive rewrite of all this .. so when that's pushed up (not sure when) i'll ping you again to try to fix this up against that code.

**Comment by Dashue** [comment]
Awesome! Will put it to good use as soon as you're done :)

**Comment by Dashue** [comment]
Will make changes to target your ver 2.0 branch for this feature

**Comment by PureKrome** [comment]
:+1:

**Comment by Dashue** [comment]
Hey, saw I had this pull request open, where did we leave off LinkedIn auth?

**Pull request closed without merging**
